"""
Regenerate src/embedded-assets.js — every runtime asset (terrain maps, the 8
destination photos, the Blender landmark GLB) inlined as base64 data URLs so the
app can be built into one self-contained HTML file (see vite.config.js).

Run from the project root:  python tools/embed_assets.py
"""
import base64, json, os

ROOT = os.path.join(os.path.dirname(__file__), '..')
PUB = os.path.join(ROOT, 'public')

FILES = {
    '/terrain/albedo.jpg': 'image/jpeg',
    '/terrain/normal.png': 'image/png',
    '/terrain/height.png': 'image/png',
    '/terrain/mask.png':   'image/png',
    '/terrain/detail.jpg': 'image/jpeg',
    '/models/sigiriya.glb': 'model/gltf-binary',
}
for k in ['anuradhapura', 'sigiriya', 'kandy', 'nuwaraeliya', 'ella', 'yala', 'galle', 'mirissa']:
    FILES['/destinations/%s.jpg' % k] = 'image/jpeg'


def main():
    embed = {}
    total = 0
    for path, mime in FILES.items():
        with open(PUB + path, 'rb') as f:
            b = f.read()
        total += len(b)
        embed[path] = 'data:%s;base64,%s' % (mime, base64.b64encode(b).decode())
    meta = json.load(open(PUB + '/terrain/meta.json'))

    js = (
        "// AUTO-GENERATED by tools/embed_assets.py — do not edit by hand.\n"
        "// All runtime assets embedded as data URLs so the app ships as one HTML file.\n"
        "export const META = " + json.dumps(meta) + ";\n"
        "export const EMBED = " + json.dumps(embed) + ";\n"
        "export const url = (p) => EMBED[p] || p;\n"
    )
    out = os.path.join(ROOT, 'src', 'embedded-assets.js')
    open(out, 'w').write(js)
    print("wrote %s (%d assets, %.1f MB raw)" % (out, len(embed), total / 1e6))


if __name__ == '__main__':
    main()
